terminal.shell = '/bin/zsh'

[general]
import = [
    "~/.config/alacritty/themes/themes/tomorrow_night.toml"
]

[window]
padding = { x = 16, y = 8 }
dynamic_title = true
opacity = 0.8
blur = true

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "CaskaydiaCove Nerd Font Mono" }
size = 14
offset = { y = 1 }

[cursor]
style = { shape = "Beam", blinking = "Always" }
