[general]
import = [
    "~/.config/alacritty/tomorrow-night-gardev.toml"
]

[window]
padding = { x = 16, y = 8 }
dynamic_title = true

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
size = 14
offset = { y = 1 }

[cursor]
style = { shape = "Beam", blinking = "Always" }

[[hints.enabled]]
regex = "https?://[^\\s]+"
hyperlinks = true
command = { program = "open" }
mouse = { enabled = true }
