# Colors (Tomorrow Night)

# Default colors
[colors.primary]
background = '#27292C'
foreground = '#c5c8c6'

[colors.cursor]
text = '#1d1f21'
cursor = '#ffffff'

# Normal colors
[colors.normal]
black   = '#1d1f21'
red     = '#cc6666'
green   = '#C2C67B'
yellow  = '#F3D086'
blue    = '#92B2CA'
magenta = '#C0A7C7'
cyan    = '#99C9C3'
white   = '#373b41'

# Bright colors
[colors.bright]
black   = '#C9C9C9'
red     = '#ff3334'
green   = '#9ec400'
yellow  = '#f0c674'
blue    = '#81a2be'
magenta = '#b77ee0'
cyan    = '#54ced6'
white   = '#282a2e'
