# Colors (Tomorrow Night)
[colors]
draw_bold_text_with_bright_colors = true

# Default colors
[colors.primary]
background = '#27292b'
foreground = '#d0d2d0'

[colors.cursor]
text = '#27292b'
cursor = '#d0d2d0'

# Normal colors
[colors.normal]
black   = '#777777'
red     = '#ca807b'
green   = '#c2c683'
yellow  = '#edd090'
blue    = '#98b0c7'
magenta = '#bba7c4'
cyan    = '#a3c7c3'
white   = '#fefefe'

# Bright colors
[colors.bright]
black   = '#999999'
red     = '#ca807b'
green   = '#c2c683'
yellow  = '#edd090'
blue    = '#98b0c7'
magenta = '#bba7c4'
cyan    = '#a3c7c3'
white   = '#fefefe'
